project:
  type: website

website:
  title: "ISSS608-VAA Alexandre Doan I wonder if the 2 things sync together or not quite odd"
  navbar:
    left:
    - text: "Hands on work"
      menu:
      - text: "Hands on exercice 1"
    right:
    - text: "This is my test placement for the header."
    - text: "This is another test to see if it works on mac"
        
format:
  html:
    theme:
      - morph
      - brand
    css: styles.css
    toc: true

editor: visual

